/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Ventanas;

/**
 *
 * @author Moises Loita
 */
public class check_out extends javax.swing.JFrame {
    
    public static Menu v1;
   
    public check_out(Menu v1) {
        initComponents();
        this.v1 = v1;
        v1.setVisible(false);
        this.setLocationRelativeTo(null);
        this.setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        TITULO = new javax.swing.JLabel();
        introduzca_name = new javax.swing.JLabel();
        input_nombre = new javax.swing.JTextField();
        volver = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        Info_hab_asig = new javax.swing.JTextArea();
        introduzca_apellido = new javax.swing.JLabel();
        input_apellido = new javax.swing.JTextField();
        check_out = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TITULO.setFont(new java.awt.Font("Arial Black", 0, 24)); // NOI18N
        TITULO.setText("Check Out");
        jPanel1.add(TITULO, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 30, -1, -1));

        introduzca_name.setText("Introduzca nombre:");
        jPanel1.add(introduzca_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 90, -1, 20));

        input_nombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                input_nombreActionPerformed(evt);
            }
        });
        jPanel1.add(input_nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 120, 230, -1));

        volver.setText("Volver");
        jPanel1.add(volver, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 310, -1, -1));

        Info_hab_asig.setColumns(20);
        Info_hab_asig.setRows(5);
        jScrollPane1.setViewportView(Info_hab_asig);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 90, 230, 180));

        introduzca_apellido.setText("Introduzca apellido:");
        jPanel1.add(introduzca_apellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 160, -1, -1));
        jPanel1.add(input_apellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 190, 230, -1));

        check_out.setText("Check out");
        jPanel1.add(check_out, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 240, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 630, 370));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void input_nombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_input_nombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_input_nombreActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(check_out.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(check_out.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(check_out.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(check_out.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new check_out(v1).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea Info_hab_asig;
    private javax.swing.JLabel TITULO;
    private javax.swing.JButton check_out;
    private javax.swing.JTextField input_apellido;
    private javax.swing.JTextField input_nombre;
    private javax.swing.JLabel introduzca_apellido;
    private javax.swing.JLabel introduzca_name;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton volver;
    // End of variables declaration//GEN-END:variables
}
