/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Ventanas;

import EDD.Cliente;
import EDD.TablaRegistro;
import EDD.ArbolB;
/**
 *
 * @author Maria
 */
public class Huespedes extends javax.swing.JFrame {

    public static Menu v1;
    private TablaRegistro registro;
    private ArbolB database;
    
    public Huespedes(Menu v1,TablaRegistro registro, ArbolB database) {
        initComponents();
        this.v1 = v1;
        v1.setVisible(false);
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        this.registro = registro;
        this.database = database;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Titulo = new javax.swing.JLabel();
        Volver = new javax.swing.JButton();
        Introduzaca_nombre = new javax.swing.JLabel();
        input_nombre = new javax.swing.JTextField();
        Introduzca_apellido = new javax.swing.JLabel();
        input_apellido = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        Datos_Huesped_Buscado = new javax.swing.JTextArea();
        Introduzca_apellido1 = new javax.swing.JLabel();
        Introduzca_apellido2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Titulo.setFont(new java.awt.Font("Arial Black", 0, 24)); // NOI18N
        Titulo.setText("Burqueda de Huespedes");
        jPanel1.add(Titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 40, -1, -1));

        Volver.setText("Volver");
        Volver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VolverActionPerformed(evt);
            }
        });
        jPanel1.add(Volver, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 330, 90, 30));

        Introduzaca_nombre.setText("Introduzca el nombre del Huesped:");
        jPanel1.add(Introduzaca_nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 120, -1, -1));
        jPanel1.add(input_nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 150, 210, -1));

        Introduzca_apellido.setText("Habitacion actual del huesped:");
        jPanel1.add(Introduzca_apellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 110, -1, 20));
        jPanel1.add(input_apellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 220, 210, -1));

        jButton1.setText("Buscar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 280, -1, -1));

        Datos_Huesped_Buscado.setEditable(false);
        Datos_Huesped_Buscado.setColumns(20);
        Datos_Huesped_Buscado.setRows(5);
        Datos_Huesped_Buscado.setFocusable(false);
        jScrollPane1.setViewportView(Datos_Huesped_Buscado);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 140, 260, 160));

        Introduzca_apellido1.setText("Introduzca el apellido del Huesped:");
        jPanel1.add(Introduzca_apellido1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 190, -1, -1));

        Introduzca_apellido2.setText("(Por favor incluir mayusculas respectivas)");
        jPanel1.add(Introduzca_apellido2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 256, -1, 20));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 670, 370));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void VolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VolverActionPerformed
        this.setVisible(false);
        Menu ventana1 = new Menu(database);
        ventana1.setVisible(true);
    }//GEN-LAST:event_VolverActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Datos_Huesped_Buscado.setText("");
        String nombre= input_nombre.getText().replaceAll("\\s+", "");
        String apellido= input_apellido.getText().replaceAll("\\s+", "");
        try{
           Cliente cliente =registro.get(nombre,apellido);
           String NumHabitacion = cliente.getHabitacion();
           Datos_Huesped_Buscado.append(NumHabitacion);
            
        }catch (Exception e){
            Datos_Huesped_Buscado.setText("El nombre introducido no se encontró\nen la base de datos");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Huespedes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Huespedes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Huespedes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Huespedes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                TablaRegistro registro = new TablaRegistro();  
                ArbolB database = new ArbolB();
                new Huespedes(v1, registro, database).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea Datos_Huesped_Buscado;
    private javax.swing.JLabel Introduzaca_nombre;
    private javax.swing.JLabel Introduzca_apellido;
    private javax.swing.JLabel Introduzca_apellido1;
    private javax.swing.JLabel Introduzca_apellido2;
    private javax.swing.JLabel Titulo;
    private javax.swing.JButton Volver;
    private javax.swing.JTextField input_apellido;
    private javax.swing.JTextField input_nombre;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
