/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Ventanas;

import EDD.TablaRegistro;
import EDD.ArbolB;
import java.nio.file.Path;
import java.nio.file.Paths;
/**
 *
 * @author Maria y Antonio
 */
public class Menu extends javax.swing.JFrame {
    private TablaRegistro registro;
    private ArbolB database;
    private ArbolB database1;
    
    // Colocar aqui todas las estructuras de datos public static para que puedan ser utilizadas en todas las ventanas
    public Menu() {
        initComponents();
        registro = new TablaRegistro();
        registro.CrearTablaReg();
        database = new ArbolB();
        String projectPath = System.getProperty("user.dir");
        String csvFile = "Booking_hotel - historico.csv";
        Path csvFilePath = Paths.get(projectPath).resolve(csvFile);
        database.Addsimpledatabase(database, csvFilePath.toString());
        
        database1 = new ArbolB();

        String projectPath1 = System.getProperty("user.dir");
        String csvFile1 = "Booking_hotel - reservas.csv";
        Path csvFilePath1 = Paths.get(projectPath1).resolve(csvFile1);
        database1.Addcomplexdatabase(database1, csvFilePath1.toString());
        this.setVisible(true);
        this.setLocationRelativeTo(null);
        this.setResizable(false);
    }
   
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Titulo_Principal = new javax.swing.JLabel();
        exit = new javax.swing.JButton();
        check_in = new javax.swing.JButton();
        check_out = new javax.swing.JButton();
        historico = new javax.swing.JButton();
        reservas = new javax.swing.JButton();
        Huespedes = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Titulo_Principal.setFont(new java.awt.Font("Arial Black", 0, 36)); // NOI18N
        Titulo_Principal.setText("Menu Principal");
        jPanel1.add(Titulo_Principal, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 40, 300, -1));

        exit.setText("X");
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });
        jPanel1.add(exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 10, 40, 30));

        check_in.setText("Check In");
        check_in.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                check_inActionPerformed(evt);
            }
        });
        jPanel1.add(check_in, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 260, 110, 60));

        check_out.setText("Check out");
        check_out.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                check_outActionPerformed(evt);
            }
        });
        jPanel1.add(check_out, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 260, 110, 60));

        historico.setText("Historico");
        historico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                historicoActionPerformed(evt);
            }
        });
        jPanel1.add(historico, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 180, 110, 60));

        reservas.setText("Reservas");
        reservas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reservasActionPerformed(evt);
            }
        });
        jPanel1.add(reservas, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 180, 110, 60));

        Huespedes.setText("Huespedes");
        Huespedes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HuespedesActionPerformed(evt);
            }
        });
        jPanel1.add(Huespedes, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 180, 110, 60));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 670, 430));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void HuespedesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HuespedesActionPerformed
        Huespedes v2 = new Huespedes(this, registro);
        v2.setVisible(true);
    }//GEN-LAST:event_HuespedesActionPerformed

    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_exitActionPerformed

    private void historicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_historicoActionPerformed
        Historico v3 = new Historico(this, database);
        v3.setVisible(true);
    }//GEN-LAST:event_historicoActionPerformed

    private void reservasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reservasActionPerformed
        Busq_Reservacion v4 = new Busq_Reservacion(this, database1);
        v4.setVisible(true);
    }//GEN-LAST:event_reservasActionPerformed

    private void check_inActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_check_inActionPerformed
        check_in v5 = new check_in(this, database1);
        v5.setVisible(true);
    }//GEN-LAST:event_check_inActionPerformed

    private void check_outActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_check_outActionPerformed
        check_out v6 = new check_out(this);
        v6.setVisible(true);
    }//GEN-LAST:event_check_outActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Huespedes;
    private javax.swing.JLabel Titulo_Principal;
    private javax.swing.JButton check_in;
    private javax.swing.JButton check_out;
    private javax.swing.JButton exit;
    private javax.swing.JButton historico;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton reservas;
    // End of variables declaration//GEN-END:variables
}
